import React from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Modal from "@/components/Modal/Modal";
export default function Home() {
  const [showModal, setShowModal] = React.useState<boolean>(true);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button
          className="bg-pink-500 text-white active:bg-pink-600 font-bold uppercase text-sm px-6 py-3 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
          type="button"
          onClick={() => setShowModal((prev) => !prev)}
        >
          Open regular modal
        </button>
        <Modal isOpen={showModal} onClose={setShowModal} />
      </main>
    </>
  );
}
